# This file was generated by GoReleaser. DO NOT EDIT.
cask "filetug" do
  binary "filetug", target: "ft"

  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "1d7d4a223a57e25e45d459aeaa1e2ce9d5d7f2437c8d86a1e0fa5aa0266e5fd3"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd573861c35e2e312d101e5e487ff97ceea3ab508d50b4c31b6a541dc4108cb9"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e9223ebf7a2da34b998df46dd4c5720ac449e30b88d2e20836fa3e05888a3da7"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cdb5b644fed977ae0e65e226182f84aad3760e8cacb5c0b6014deccbb00b4026"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_linux_arm64.tar.gz"
    end
  end

  name "filetug"
  desc "FileTug – modern CLI file browser/picker with neat UI"
  homepage "https://github.com/filetug/filetug"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filetug"

  # No zap stanza required

end
