# This file was generated by GoReleaser. DO NOT EDIT.
cask "filetug" do
  binary "filetug", target: "ft"

  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "ba3fe174c459e773de9918248d9f2a2f5b26646e32bfff4553a7c4c15933643b"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "95e2e8600e572ee2f1541bc59b71b2e8ab24a8262f6608b56c36f6beacfe53ec"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5688c70a93ce9227deae63f9285e4e857ab0efb2c2d70f3f98f19eccdfe780c1"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "16e46049b2ed53f67aa224063a91c77c63d4f594958cf64c7fe6f78c5c83ce07"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_linux_amd64.tar.gz"
    end
  end

  name "filetug"
  desc "FileTug – modern CLI file browser/picker with neat UI"
  homepage "https://github.com/filetug/filetug"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filetug"

  # No zap stanza required
end
