# This file was generated by GoReleaser. DO NOT EDIT.
cask "filetug" do
  binary "filetug", target: "ft"

  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "402a102444de16620d3a49a6abc5abfab73ad310f867d25fd930844662f0f08b"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e204c33a76add57e95528e58ce834e8347b4ed211b4003ccaa7d8e6e2b93671"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "221e04753128cb7ae20c9ac6975ad457c893e861a2f84adb8b085dc82749b7ee"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b79ab51c2853151c7fa83ab5a479b787bd659456099a8aec70f3179047d2850"
      url "https://github.com/filetug/filetug/releases/download/v#{version}/filetug_#{version}_linux_amd64.tar.gz"
    end
  end

  name "filetug"
  desc "FileTug – modern CLI file browser/picker with neat UI"
  homepage "https://github.com/filetug/filetug"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "filetug"

  # No zap stanza required
end
